abstract type ISAECourse <: IEntity end
abstract type ISAELigne <: IEntity end
abstract type ISAEChainage <: IEntity end
abstract type ISAEPointChaine <: IEntity end
abstract type ISAEDestination <: IEntity end
abstract type ISAEPoint <: IEntity end
abstract type ISAEInterPoint <: IEntity end
abstract type ISAECalendrier <: IEntity end
abstract type ISAECJDV <: IEntity end
abstract type ISAEHoraire <: IEntity end
abstract type ISAEPeriodeHoraire <: IEntity end
abstract type ISAERefCourse <: IEntity end
abstract type ISAERecArret <: IEntity end
abstract type ISAERecHoraire <: IEntity end
abstract type ISAERecManoeuvre <: IEntity end
abstract type ISAERecVehicule <: IEntity end
abstract type IAppUserRoleAsso <: IEntity end
abstract type IRoleRoleAsso <: IEntity end
abstract type IRole <: IEntity end
abstract type IFile <: IEntity end
abstract type IHorairePrevisionnel <: IEntity end
abstract type ISAERefPoint <: IEntity end
abstract type ISAEVersPoint <: IEntity end
abstract type IPassageArret <: IEntity end
abstract type IETLImportProcess <: IEntity end
abstract type IETLTransformProcess <: IEntity end
abstract type IAnomalieDef <: IEntity end
abstract type IAnomalie <: IEntity end
abstract type IRegulationIntervalle <: IEntity end
abstract type IPeriodeTopo <: IEntity end
abstract type IIntervalle <: IEntity end
abstract type ICauseAnomalieType <: IEntity end
abstract type ICauseAnomalie <: IEntity end
abstract type ICauseAnomalieFichierAsso <: IEntity end
abstract type ICauseAnomalieHorairePrevisionnelAsso <: IEntity end
abstract type IFranchiseMensuelleKmNonFaits <: IEntity end
abstract type IFrontendVersion <: IEntity end
abstract type IScheduledTaskExecution <: IEntity end
