include("compute_respiratoryRate_FiO2_SPO2_WSO2trunc.jl")
include("computePao2OverFio2.jl")
include("computePositiveExpiratoryPressure.jl")
include("computeRespiratoryVolumeMinute.jl")
include("computeUnplugAttemptInvasiveVentilation.jl")
include("computeVentilationTypeAndDebitO2.jl")
