function computeVentilationTypeAndDebitO2 end
function computeUnplugAttemptInvasiveVentilation end
function computeRespiratoryVolumeMinute end
function computeRespiratoryRate end
function computeFio2 end
function computePao2OverFio2 end
function computePositiveExpiratoryPressure end