function preparePatientsFromRawExcelFile end
function getPatientDFFromExcel end
function cutPatientDF end
function initializeWindow end
function refineWindow1stPass! end
function refineWindow1stPass end
function refineWindow2ndPass! end
function processPatientRawHistory end
function combineRefinedWindows end
function enrichResultsOfRefiningModule! end
function getRefiningFunctions end
function get1stPassRefiningFunctions end
function get2ndPassRefiningFunctions end

# Refining functions
