function computeVolumeInOut end
function computeVolumePerfusion end
function computeVolumeAndTypeVascularFilling end
function computeVolumeMedecine end
function computeVolumeEnteralFeeding end
function computeVolumeParentalFeeding end